name: Sameer Sengupta
favicon: null
layout_spectrum: 0.9472312075085938
typography_spectrum: 0.3800158449448645
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.8441049924585968
  saturation: 0.3461171705275774
  rhythmicContrast: 0.687710763188079
purpose: []
